export const categories = [
  { name: "لیوان‌های کاغذی", slug: "cups", description: "لیوان گرم و سرد برای کافه، بیرون‌بر و رویداد" },
  { name: "کاسه‌های کاغذی", slug: "bowls", description: "کاسه غذا، سالاد و سوپ با بدنه کرافت یا سفید" },
  { name: "درب‌ها", slug: "lids", description: "درب لیوان و متعلقات مصرفی برای سرو حرفه‌ای" },
  { name: "کارتن پیتزا", slug: "pizza", description: "جعبه پیتزا و فست‌فود در سایزهای استاندارد" },
  { name: "کاغذ دورپیچ", slug: "paper", description: "کاغذ ساندویچ، شیرینی و بسته‌بندی تماس مستقیم با غذا" },
];

export const products = [
  {
    id: "cup-220-kraft",
    name: "لیوان ۲۲۰cc یکروکرافت سوئدی",
    slug: "cup-220-kraft",
    sku: "CUP-220-KRAFT",
    category: "cups",
    price: 890000,
    image: "/mock-products/cup-220-kraft.svg",
    featured: true,
    unit: "کارتن ۱۰۰۰ عددی",
    minOrder: "۱ کارتن",
    leadTime: "آماده ارسال ۲۴ تا ۴۸ ساعت",
    material: "کاغذ یکروکرافت با پوشش داخلی",
    suitableFor: ["قهوه بیرون‌بر", "رویداد", "کافه"],
    specs: [
      ["حجم", "۲۲۰ سی‌سی"],
      ["تعداد در کارتن", "۱۰۰۰ عدد"],
      ["رنگ", "کرافت طبیعی"],
      ["چاپ اختصاصی", "از ۱۰ کارتن"],
    ],
  },
  {
    id: "vip-360-white",
    name: "لیوان VIP ۳۶۰cc سفید مات",
    slug: "vip-360-white",
    sku: "VIP-360-WHITE",
    category: "cups",
    price: 1280000,
    image: "/mock-products/vip-360-white.svg",
    featured: true,
    unit: "کارتن ۱۰۰۰ عددی",
    minOrder: "۱ کارتن",
    leadTime: "آماده ارسال ۲ تا ۳ روز کاری",
    material: "کاغذ سفید مات با لمینیت داخلی",
    suitableFor: ["لاته و کاپوچینو", "برندینگ کافه", "سرو VIP"],
    specs: [
      ["حجم", "۳۶۰ سی‌سی"],
      ["تعداد در کارتن", "۱۰۰۰ عدد"],
      ["رنگ", "سفید مات"],
      ["درب سازگار", "درب VIP"],
    ],
  },
  {
    id: "bowl-750-kraft",
    name: "کاسه ۷۵۰cc دورو کرافت",
    slug: "bowl-750-kraft",
    sku: "BOWL-750-KRAFT",
    category: "bowls",
    price: 1560000,
    image: "/mock-products/bowl-750-kraft.svg",
    featured: true,
    unit: "کارتن ۳۰۰ عددی",
    minOrder: "۲ کارتن",
    leadTime: "آماده ارسال ۲۴ ساعت",
    material: "کرافت دورو با پوشش مقاوم به رطوبت",
    suitableFor: ["سالاد", "سوپ", "غذای گرم"],
    specs: [
      ["حجم", "۷۵۰ سی‌سی"],
      ["تعداد در کارتن", "۳۰۰ عدد"],
      ["رنگ", "کرافت"],
      ["مقاومت", "مناسب سرد و گرم"],
    ],
  },
  {
    id: "vip-lid-black",
    name: "درب پلیمری لیوان VIP",
    slug: "vip-lid-black",
    sku: "LID-VIP-BLACK",
    category: "lids",
    price: 620000,
    image: "/mock-products/vip-lid-black.svg",
    featured: false,
    unit: "کارتن ۱۰۰۰ عددی",
    minOrder: "۱ کارتن",
    leadTime: "آماده ارسال ۲۴ ساعت",
    material: "پلیمر غذایی مشکی",
    suitableFor: ["لیوان VIP", "نوشیدنی داغ", "بیرون‌بر"],
    specs: [
      ["تعداد در کارتن", "۱۰۰۰ عدد"],
      ["رنگ", "مشکی"],
      ["سازگاری", "لیوان VIP ۳۶۰"],
      ["نوع مصرف", "نوشیدنی داغ"],
    ],
  },
  {
    id: "pizza-box-30",
    name: "کارتن پیتزا سوئدی ۳۰",
    slug: "pizza-box-30",
    sku: "PIZZA-30-SWEDISH",
    category: "pizza",
    price: 2100000,
    image: "/mock-products/pizza-box-30.svg",
    featured: true,
    unit: "بسته ۱۰۰ عددی",
    minOrder: "۵ بسته",
    leadTime: "آماده ارسال ۳ روز کاری",
    material: "کارتن سوئدی بهداشتی",
    suitableFor: ["پیتزا ۳۰ سانت", "فست‌فود", "چاپ لوگو"],
    specs: [
      ["ابعاد", "۳۰ × ۳۰ سانتی‌متر"],
      ["تعداد در بسته", "۱۰۰ عدد"],
      ["جنس", "سوئدی"],
      ["چاپ اختصاصی", "از ۲۰ بسته"],
    ],
  },
  {
    id: "wrap-paper-striped",
    name: "کاغذ دورپیچ قهوه‌ای راه‌راه",
    slug: "wrap-paper-striped",
    sku: "PAPER-STRIPED",
    category: "paper",
    price: 740000,
    image: "/mock-products/wrap-paper-striped.svg",
    featured: false,
    unit: "بسته ۱۰ کیلوگرمی",
    minOrder: "۱ بسته",
    leadTime: "آماده ارسال ۲۴ ساعت",
    material: "کاغذ تماس مستقیم با غذا",
    suitableFor: ["ساندویچ", "شیرینی", "کافه"],
    specs: [
      ["وزن بسته", "۱۰ کیلوگرم"],
      ["طرح", "راه‌راه قهوه‌ای"],
      ["کاربرد", "تماس مستقیم با غذا"],
      ["برش اختصاصی", "قابل سفارش"],
    ],
  },
];

export const posts = [
  { slug: "kraft-packaging-guide", title: "راهنمای انتخاب ظروف کرافت برای کافه‌ها", excerpt: "چطور بین لیوان، کاسه و کاغذ دورپیچ انتخاب بهتری داشته باشیم." },
  { slug: "custom-print", title: "چاپ اختصاصی روی بسته‌بندی غذا", excerpt: "نکات مهم برای آماده‌سازی فایل، تیراژ و کنترل کیفیت." },
  { slug: "food-safe-paper", title: "استاندارد تماس مستقیم با غذا", excerpt: "چه چیزهایی در کاغذ و پوشش ظروف مهم است؟" },
];
